/*******************************************************************************
        ssl_cgi.c
        Copyright (c) 2006, Rabbit Semiconductor.

        A simple web-counter implemented in CGI functions. This
        demonstrates how to add basic dynamic functionality to
        your pages.

		  This program has been modified to use SSL via HTTPS. See the
        SSL comments below for more information.

        ***NOTE*** This sample will NOT compile without first creating a
        certificate with the name and path specified in the #ximport line
        ("#ximport 'cert\mycerts.pem' server_pub_cert") below. See the SSL
        Walkthrough, Section 4.1 in the SSL User's Manual for information
        on creating certificates for SSL programs.

        As of Dynamic C 10.66, it is recommended to use .pem format
        certificates rather than the deprecated .dcc format.  Both formats
        are generated by the certificate utility, however .pem is faster
        at run-time, and is a non-proprietary format.

*******************************************************************************/
#class auto


/***********************************
 * Configuration                   *
 * -------------                   *
 * All fields in this section must *
 * be altered to match your local  *
 * network settings.               *
 ***********************************/

/*
 * NETWORK CONFIGURATION
 * Please see the function help (Ctrl-H) on TCPCONFIG for instructions on
 * compile-time network configuration.
 */
#define TCPCONFIG 1


/*
 * Web server configuration
 */

/*
 * only one socket and server are needed for a reserved port
 */
#define HTTP_MAXSERVERS 1
#define MAX_TCP_SOCKET_BUFFERS 1

// This macro determines the number of HTTP servers that will use
// SSL (HTTPS servers). In this case, we have 1 and this defines
// it to be HTTPS
#define HTTP_SSL_SOCKETS 1


// SSL Stuff
// This macro tells the HTTP library to use SSL
#define USE_HTTP_SSL
// Defining this macro tells SSL to enable AES.
// AES_CRYPT.LIB must be available and support SSL (v1.05 or greater)
//#define SSL_USE_AES
// This macro tells SSL to disable RC4
// IMPORTANT: At least one cipher (RC4 or AES) must be enabled.
//#define SSL_DONT_USE_RC4

// Import the certificate and corresponding private key.
// The Dynamic C Certificate Generation Utility will create these files
// (if XXX is the basic certificate name, then the files will be called
// XXXs.pem and XXXkey.pem).
#ximport "cert\mycerts.pem" server_pub_cert
#ximport "cert\mycertkey.pem" server_priv_key

/********************************
 * End of configuration section *
 ********************************/


#define TIMEZONE        -8

#memmap xmem
#use "dcrtcp.lib"
#use "http.lib"

#ximport "pages/cgi.html"    	index_html
#ximport "pages/rabbit1.gif"    rabbit1_gif

/*
 *  Notice that cgi doesn't have a MIME type or a handler.
 *  The handler for this type of entity is make the the HttpSpec
 *  structure.
 *
 */


/* the default mime type for '/' must be first */
const HttpType http_types[] =
{
   { ".html", "text/html", NULL},
   { ".gif", "image/gif", NULL},
   { ".cgi", "", NULL}
};


/*
 *  there is a new entry in the http_flashspec:  "/test.cgi"
 *
 *  This entry includes the online name of CGI routine and the
 *  internal routine that it maps to.
 *
 */

int test_cgi(HttpState* state);

const HttpSpec http_flashspec[] =
{
   { HTTPSPEC_FILE,  "/",              index_html,    NULL, 0, NULL, NULL},
   { HTTPSPEC_FILE,  "/index.html",    index_html,    NULL, 0, NULL, NULL},
   { HTTPSPEC_FILE,  "/rabbit1.gif",   rabbit1_gif,   NULL, 0, NULL, NULL},

   { HTTPSPEC_FUNCTION, "/test.cgi",   0, test_cgi, 0, NULL, NULL}
};


void main()
{
	SSL_Cert_t my_cert;

	// Start network and wait for interface to come up (or error exit).
	sock_init_or_exit(1);
   http_init();

	memset(&my_cert, 0, sizeof(my_cert));
	// When using HTTPS (i.e. HTTP over SSL or TLS), the certificates need
	// to be parsed and registered with the library.  For use with a
	// server, we need to know our own private key.
	if (SSL_new_cert(&my_cert, server_pub_cert, SSL_DCERT_XIM, 0) ||
	    SSL_set_private_key(&my_cert, server_priv_key, SSL_DCERT_XIM))
		exit(7);

	// Register certificate with HTTPS server.
	https_set_cert(&my_cert);

   tcp_reserveport(443);

/*
 *  http_handler needs to be called to handle the active http servers.
 */

   while (1) {
      http_handler();
   }
}

/*
 *  test string what is served by test_cgi.  It is used
 *  as one of the parameters to sprintf() to build a buffer
 *  that is later sent.  The format of the first three lines
 *  is important.
 *
 *  HTTP/1.0 200 OK\r\n
 *  Date: <current date/time from http_date_str()>\r\n
 *  Content-Type: text/html\r\n\r\n
 *
 *  The first line tells the internet browser that the content
 *  was found and will be returned in the body.  The next line
 *  is the date which is followed by the mime type of the body.
 *  Notice the \r\n\r\n.  If you leave out the second \r\n the
 *  browser will assume that the next line is part of the header.
 *  The document follows.
 *
 *  There are many books and online references for the format
 *  of CGI responses.
 *
 */

const char teststr[] =
	"HTTP/1.0 200 OK\r\n" \
	"Date: %s" \
	"Content-Type: text/html\r\n\r\n" \
	"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD W3 HTML//EN\">\r\n" \
	"<HTML>" \
	"<HEAD><TITLE><cgi.c></TITLE></HEAD>" \
	"<BODY><H1>cgi.c, hit count %d</H1>" \
	"      <BR><BR><BR><A HREF=\"/index.html\">home</A>" \
	"</BODY>" \
	"</HEAD>";

/*
 *  This is the internal cgi routine.  It uses teststr to build
 *  a buffer which it uses to respond to the request.
 *
 *  This routine increments the hit count value and uses the
 *  cgi_sendstring routine to send the page.  The cgi_sendstring
 *  routine immediately returns and the string is sent the next
 *  time this server gets a tick.  If you want the server to
 *  immediately close the connection return a one otherwise you
 *  should return a zero.
 *
 */

int test_cgi(HttpState* state)
{
	static char date[30];
	static char buffer[512];
	static int hitcount;

	#GLOBAL_INIT { hitcount=0; }

	hitcount++;
	http_date_str(date);

	sprintf(buffer,teststr,date,hitcount);

	cgi_sendstring(state,buffer);
   return 0;
}