// Legacy Dynamic C keywords, defined as macros to the new keywords.

#define abandon     __abandon
#define abort       __abort
#define always_on   __always_on
#define anymem      __anymem
#define bbram       __bbram
#define cofunc      __cofunc
#define costate     __costate
#define debug       __debug
#define everytime   __everytime
#define far         __far
#define firsttime   __firsttime
#define init_on     __init_on
#define interrupt   __interrupt
#define near        __near
#define nodebug     __nodebug
#define norst       __norst
#define nouseix     __nouseix
#define protected   __protected
#define root        __root
#define scofunc     __scofunc
#define segchain    __segchain
#define shared      __shared
#define slice       __slice
#define useix       __useix
#define waitfor     __waitfor
#define waitfordone __wfd
#define wfd         __wfd
#define xdata       __xdata
#define xmem        __xmem
#define xstring     __xstring
#define yield       __yield
