# Make file written June 2009 by Tom Collins

all: triplets.exe BL_triplets.exe

triplets.exe: triplets.cpp
	g++ -O2 -Wall -o triplets.exe triplets.cpp

BL_triplets.exe: BL_triplets.cpp
	g++ -O2 -Wall -o BL_triplets.exe BL_triplets.cpp