######################################
#
# 	Samples\LCD_Keypad\UNIX\Makefile
#	Z-World, 2002
#

CC = gcc
CFLAGS = -Wall

#  Name the programs created here:
EXECS = pcrespond pcsend

#
# -------------------------------------
#

all :	$(EXECS)

clean :
	rm -f *.o $(EXECS) *~


#
# -------------------------------------
#

pcrespond :	pcrespond.c

pcsend :	pcsend.c
